'use client';
import {loadJournal,saveJournal,deleteEntry} from '@/lib/storage';
import LocalPhoto from './LocalPhoto';
import Backup from './Backup';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Plus,Activity,Utensils,Clock3,ArrowUpRight,Camera,Settings2,Trash2,ChevronRight,Scale,Check,Leaf,Flame,BookOpen} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription,EmptyMedia} from '@/components/ui/empty';
import {Progress} from '@/components/ui/progress';
import {Toaster,toast} from 'sonner';
import {foods,nutrition,defaultProfile,fastingStatus,clockLabel,weekPlan,snack,type Portion} from '@/lib/nutrition';
type Entry={id:string;kind:string;day:string;name?:string;time?:string;calories?:number;protein?:number;carbs?:number;fat?:number;fiber?:number;notes?:string;items?:Portion[];hasPhoto?:boolean;type?:string;minutes?:number;intensity?:string;kg?:number};
type Profile=typeof defaultProfile;
const num=(n:number)=>Math.round(n).toLocaleString();
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function Choice({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.value} value={i.value}>{i.label}</SelectItem>)}</SelectContent></Select>}
const simple=(values:string[])=>values.map(v=>({value:v,label:v}));
export default function Journal(){
 const [profile,setProfile]=useState<Profile>(defaultProfile),[records,setRecords]=useState<Entry[]>([]),[status,setStatus]=useState('loading'),[error,setError]=useState(''),[date,setDate]=useState(''),[now,setNow]=useState<Date|null>(null),[tab,setTab]=useState('journal');
 const [dialog,setDialog]=useState<string|null>(null),[draft,setDraft]=useState<{name:string;items:Portion[]}|undefined>(),[saving,setSaving]=useState(false),[formError,setFormError]=useState(''),[deleting,setDeleting]=useState<Entry|null>(null),[planDay,setPlanDay]=useState('0');
 const stateRef=useRef({records,date});stateRef.current={records,date};
 async function load(){try{setError('');const data=await loadJournal();setRecords(data.records);setProfile({...defaultProfile,...data.profile});setStatus('ready')}catch(e){setStatus('error');setError(e instanceof Error?e.message:'Could not load your journal.')}}
 useEffect(()=>{setDate(today());setNow(new Date());setPlanDay(String((new Date().getDay()+6)%7));void load();const timer=setInterval(()=>setNow(new Date()),30000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=(tool:unknown)=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(console.error)}catch(e){console.error(e)}};register({name:'start_meal_logging',title:'Start logging a meal',description:'Open the meal-entry form. This does not save a meal.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object.');setDraft(undefined);setFormError('');setDialog('meal');return {status:'meal_form_open'}}});register({name:'read_selected_day',title:'Read the selected day',description:'Read saved meals and exercise totals for the date selected in the journal.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object.');const s=stateRef.current;return {date:s.date,records:s.records.filter(r=>r.day===s.date)}}});return()=>lifecycle.abort()},[]);
 const entries=records.filter(r=>r.day===date),meals=entries.filter(r=>r.kind==='meal'),workouts=entries.filter(r=>r.kind==='exercise');
 const total=meals.reduce((a,r)=>({calories:a.calories+(r.calories||0),protein:a.protein+(r.protein||0),carbs:a.carbs+(r.carbs||0),fat:a.fat+(r.fat||0),fiber:a.fiber+(r.fiber||0)}),{calories:0,protein:0,carbs:0,fat:0,fiber:0});
 const minutes=workouts.reduce((a,r)=>a+(r.minutes||0),0),fast=now?fastingStatus(profile.start,now):null;
 const weights=records.filter(r=>r.kind==='weight').sort((a,b)=>a.day.localeCompare(b.day));const latest=weights.at(-1)?.kg||profile.weight;
 const selected=weekPlan[Number(planDay)],planTotal=nutrition([...selected.a,...selected.b,...snack]);
 function open(kind:string){setDraft(undefined);setFormError('');setDialog(kind)}
 async function save(kind:string,data:unknown,photo?:File){if(saving)return;setSaving(true);setFormError('');try{await saveJournal(kind,date,data,photo);setDialog(null);toast.success(kind==='profile'?'Your settings are saved.':'Added to your journal.');await load()}catch(e){setFormError(e instanceof Error&&e.name!=='ZodError'?e.message:'Please check the entry values. Your input is still here.')}finally{setSaving(false)}}
 async function remove(){if(!deleting)return;setSaving(true);try{await deleteEntry(deleting.id);setDeleting(null);toast.success('Entry removed.');await load()}catch(e){toast.error(e instanceof Error?e.message:'Could not delete. Please retry.')}finally{setSaving(false)}}
 function useMeal(name:string,items:Portion[]){setDraft({name,items});setFormError('');setDialog('meal')}
 return <main className="shell"><Toaster richColors/><header><a className="brand" href="./">s<span>t</span>ride<span className="brand-dot">.</span></a><div className="header-right"><span className="private">FOOD & MOVEMENT · YOUR JOURNAL</span><button className="icon-button" onClick={()=>open('profile')} aria-label="Profile and eating window"><Settings2 size={20}/></button></div></header>
 <div className="heading"><div><p className="eyebrow">ONE DAY AT A TIME</p><h1>Fuel your next move.</h1><p>Eat well. Train with energy. Build a rhythm that lasts.</p></div><button className="primary" onClick={()=>open('meal')} disabled={status!=='ready'}><Plus size={18}/> Log a meal</button></div>
 {status==='loading'&&<div className="notice" role="status">Opening your journal…</div>}{error&&<div className="notice error" role="alert">{error} <button onClick={load}>Retry</button></div>}
 <Backup onRestore={load}/>{status==='ready'&&!profile.weight&&<div className="notice">Set your starting measurements and longer-term goal. <button onClick={()=>open('profile')}>Set up your profile</button></div>}<div className="overview"><section className="fast-card"><div className="row"><span className="pill"><Clock3 size={15}/> YOUR 16:8 RHYTHM</span><button className="text-light" onClick={()=>open('profile')}>Adjust <ArrowUpRight size={14}/></button></div><h2>{fast?(fast.eating?'Your window is open.':'Time to rest & reset.'):'Find your daily rhythm.'}</h2><p>{fast?`${Math.floor(fast.remaining/60)}h ${fast.remaining%60}m until your eating window ${fast.eating?'closes':'opens'}.`:'Eight hours to eat. Sixteen hours to fast.'}<br/>A schedule to support you, not a rule to push through.</p><div className="time-track"><i style={{width:`${(fast?.progress||0)*100}%`,marginLeft:0}}/></div><div className="row"><span>{profile.start} · first meal</span><span>{clockLabel((fast?.start??720)+480)} · finish eating</span></div><span className="tiny light">Live schedule · your device’s local time</span></section>
 <section className="card"><div className="row"><Utensils className="accent" size={22}/><span className="tag">{date===today()?'TODAY':'SELECTED DAY'}</span></div><h3>Nutrition at a glance</h3><div className="big-number">{status==='ready'?num(total.calories):'—'} <small>kcal logged</small></div>{profile.calorieTarget>0?<><Progress value={Math.min(100,total.calories/profile.calorieTarget*100)} aria-label="Logged calories relative to your chosen target"/><p className="tiny">Your chosen guide: {num(profile.calorieTarget)} kcal · estimates</p></>:<p className="tiny">A picture of what you’ve logged.</p>}<div className="macro-grid"><span>Protein<strong>{num(total.protein)} g</strong></span><span>Carbs<strong>{num(total.carbs)} g</strong></span><span>Fat<strong>{num(total.fat)} g</strong></span></div></section>
 <section className="card"><div className="row"><Activity className="accent" size={22}/><span className="tag">{workouts.length} SESSIONS</span></div><h3>Movement</h3><div className="big-number">{status==='ready'?minutes:'—'} <small>minutes logged</small></div><p className="tiny">Running, tennis, Muay Thai —<br/>and space to recover.</p><button className="secondary full" onClick={()=>open('exercise')} disabled={status!=='ready'}>Log exercise <ArrowUpRight size={16}/></button></section></div>
 <Tabs value={tab} onValueChange={setTab}><div className="journal-toolbar"><TabsList className="main-tabs" variant="line"><TabsTrigger value="journal">Daily journal</TabsTrigger><TabsTrigger value="plan">7-day eating plan</TabsTrigger><TabsTrigger value="progress">Your progress</TabsTrigger></TabsList><label className="date-control"><span className="sr-only">Journal date</span><input type="date" value={date} max={today()} onChange={e=>{if(e.target.value)setDate(e.target.value)}}/></label></div>
 <TabsContent value="journal"><div className="journal-grid"><div><section className="card meal-section"><div className="section-heading"><div><p className="eyebrow">FOOD DIARY</p><h3>Your plate, in perspective.</h3></div><button className="icon-button" aria-label="Add meal" disabled={status!=='ready'} onClick={()=>open('meal')}><Plus size={20}/></button></div>{meals.length===0?<Empty className="empty-meals"><EmptyHeader><EmptyMedia variant="icon"><Camera/></EmptyMedia><EmptyTitle>What’s on your plate?</EmptyTitle><EmptyDescription>Add a photo and the foods you ate.<br/>Confirm portions to estimate your nutrition.</EmptyDescription></EmptyHeader><button className="primary" disabled={status!=='ready'} onClick={()=>open('meal')}><Plus size={16}/> Add your first meal</button><p className="tiny">Photos are saved with meals. Food recognition is not connected.</p></Empty>:<div className="entry-list">{meals.map(r=><article className="meal-entry" key={r.id}>{r.hasPhoto?<LocalPhoto id={r.id} name={r.name}/>:<div className="meal-placeholder"><Utensils size={24}/></div>}<div className="entry-content"><span className="tiny">{r.time} · Estimated nutrition</span><h4>{r.name}</h4><p>{num(r.calories||0)} kcal <span>· P {num(r.protein||0)} g · C {num(r.carbs||0)} g · F {num(r.fat||0)} g</span></p>{r.notes&&<p className="tiny">{r.notes}</p>}</div><button className="icon-button" aria-label={'Delete '+r.name} onClick={()=>setDeleting(r)}><Trash2 size={16}/></button></article>)}</div>}</section>
 <section className="card workout-section"><div className="section-heading"><h3>Training & recovery</h3><button className="text-button" onClick={()=>open('exercise')} disabled={status!=='ready'}>Add session <Plus size={16}/></button></div>{workouts.length?workouts.map(r=><div className="exercise-entry" key={r.id}><span className="activity-icon"><Activity size={20}/></span><div className="entry-content"><h4>{r.type}</h4><p>{r.minutes} min · {r.intensity}{r.notes?' · '+r.notes:''}</p></div><button className="icon-button" aria-label={'Delete '+r.type+' session'} onClick={()=>setDeleting(r)}><Trash2 size={16}/></button></div>):<p className="muted">No sessions logged for this day. Easy movement and rest count, too.</p>}</section></div>
 <aside><section className="card analysis-card"><span className="label-icon"><Leaf size={18}/> YOUR DAILY CHECK-IN</span><h3>{meals.length?'Build on what’s here.':'A little awareness goes a long way.'}</h3>{meals.length?<><div className="analysis-point"><Check size={17}/><div><strong>{num(total.protein)} g of protein logged</strong><p>Spread protein foods across your meals to support recovery.</p></div></div><div className="analysis-point"><Leaf size={17}/><div><strong>{num(total.fiber)} g of fiber logged</strong><p>{total.fiber<25?'Add vegetables, fruit, beans or whole grains to your next meal.':'Your logged foods include fiber. Keep a variety of plant foods in the mix.'}</p></div></div><div className="analysis-point"><Activity size={17}/><div><strong>{workouts.some(w=>w.intensity==='Hard')?'Fuel the hard session.':'Make room for recovery.'}</strong><p>{workouts.some(w=>w.intensity==='Hard')?'Include carbohydrates around training, then a meal with protein and carbohydrates.':'Keep meals regular, drink to thirst, and allow easier training days.'}</p></div></div></>:<p>Once you log a meal, you’ll see your protein, fiber, and practical ideas for your next plate.</p>}<p className="tiny">Based only on your logged foods. Generic estimates cannot assess your full nutritional needs.</p></section>
 <section className="goal-note"><span className="eyebrow">A HEALTHIER PACE</span><h3>Think months, not a deadline.</h3><p>Aim for about 0.5–1 kg per week. Your goal deserves time, good food, and enough energy to train.</p><button className="text-button" onClick={()=>setTab('plan')}>See your plan <ChevronRight size={16}/></button></section></aside></div></TabsContent>
 <TabsContent value="plan"><div className="plan-top card"><div><p className="eyebrow">YOUR STARTING TEMPLATE</p><h2>Two meals. One useful snack.</h2><p>Built around your {profile.start}–{clockLabel((fast?.start??720)+480)} window. Adjust portions to hunger, training, progress, and professional guidance.</p></div><div className="plan-day"><Choice value={planDay} onChange={setPlanDay} label="Day of meal plan" items={weekPlan.map((d,i)=>({value:String(i),label:d.day}))}/><p>About <strong>{num(planTotal.calories)} kcal</strong><br/>{num(planTotal.protein)} g protein · example day</p></div></div>
 <div className="plan-meals">{[{n:'01',time:profile.start,title:selected.lunch,items:selected.a},{n:'02',time:clockLabel((fast?.start??720)+240),title:'Yogurt, oats, banana & almonds',items:snack},{n:'03',time:clockLabel((fast?.start??720)+450),title:selected.dinner,items:selected.b}].map(m=><section className="card recipe" key={m.n}><div className="row"><span className="meal-number">{m.n}</span><span className="tag">{m.time}</span></div><h3>{m.title}</h3><ul>{m.items.map(i=><li key={i.id}><span>{foods.find(f=>f.id===i.id)?.name}</span><strong>{i.grams} g</strong></li>)}</ul><div className="recipe-bottom"><p>{num(nutrition(m.items).calories)} kcal · {num(nutrition(m.items).protein)} g protein</p><button className="secondary full" disabled={status!=='ready'} onClick={()=>useMeal(m.title,m.items)}>Review & log this meal <Plus size={16}/></button></div></section>)}</div>
 <div className="notice">This sample menu is not a calorie prescription or an allergy-filtered plan. It includes fish, dairy, eggs, wheat, soy, and nuts across the week. Review ingredients and make appropriate substitutions. Weights are cooked unless labeled dry.</div>
 <div className="guidance-grid"><section className="card"><Clock3 className="accent"/><h3>Make 16:8 work for you</h3><p>Start with noon–8 pm if it fits your life. Water and unsweetened tea or black coffee can fit the fasting period. Time restriction is one way to structure eating; it does not guarantee weight loss.</p><p>Shift the window earlier for morning training or later for evening sessions. If a long fast leaves you weak or affects recovery, use a wider window and seek advice.</p><button className="text-button" onClick={()=>open('profile')}>Adjust eating window <ArrowUpRight size={16}/></button></section><section className="card"><Flame className="accent"/><h3>Fuel running, tennis & Muay Thai</h3><p>Place hard sessions inside your eating window when possible. Have a comfortable meal 2–3 hours before, or a light carbohydrate snack nearer training. Eat protein and carbohydrates afterward.</p><p>Alternate hard and easy days. Keep at least one lighter recovery day each week. Don’t subtract workout calories from food or use extra exercise to compensate for a meal.</p></section><section className="card"><Scale className="accent"/><h3>A realistic first month</h3><p>About 0.5–1 kg per week is a gradual direction for many adults. Individual results vary, and early scale changes include water. Give your longer-term goal enough time.</p><p>Review your weekly weight trend, hunger, sleep, and performance. A clinician or dietitian can set an appropriate energy target, especially with daily intense training.</p></section></div>
 <div className="medical-note"><strong>Before fasting:</strong> get medical advice if you use glucose-lowering medication, have diabetes, are pregnant or breastfeeding, or have a history of eating disorders. Stop fasting or exercise if you feel faint or unwell. This plan is for adults and does not replace individual clinical advice.</div>
 <div className="sources">Guidance: <a href="https://www.cdc.gov/healthy-weight-growth/losing-weight/index.html" target="_blank" rel="noreferrer">CDC · gradual weight loss</a><a href="https://www.niddk.nih.gov/health-information/professionals/diabetes-discoveries-practice/patients-intermittent-fasting" target="_blank" rel="noreferrer">NIDDK · fasting</a><a href="https://www.eatright.org/fitness/physical-activity/exercise-nutrition/timing-your-pre-and-post-workout-nutrition" target="_blank" rel="noreferrer">Academy of Nutrition and Dietetics · workout meals</a></div></TabsContent>
 <TabsContent value="progress"><div className="progress-layout"><section className="card"><p className="eyebrow">YOUR LONGER-TERM DIRECTION</p><div className="weight-direction"><strong>{latest?latest.toFixed(1):'—'}<small> kg current</small></strong><ChevronRight/><strong>{profile.goalWeight||'—'}<small> kg aspiration</small></strong></div><p>Starting point: {profile.weight||'—'} kg · Height: {profile.height?(profile.height/100).toFixed(2):'—'} m</p><p>Look at trends over weeks. Daily changes often reflect fluid, food, and recovery.</p><button className="primary" onClick={()=>open('weight')} disabled={status!=='ready'}><Plus size={16}/> Log weight</button></section><section className="card"><h3>Your weigh-ins</h3>{weights.length?weights.slice().reverse().map(r=><div className="weight-row" key={r.id}><span>{r.day}</span><strong>{r.kg?.toFixed(1)} kg</strong><button className="icon-button" aria-label={'Delete weight from '+r.day} onClick={()=>setDeleting(r)}><Trash2 size={16}/></button></div>):<Empty><EmptyHeader><EmptyMedia variant="icon"><Scale/></EmptyMedia><EmptyTitle>Start with a check-in</EmptyTitle><EmptyDescription>Weigh under similar conditions, such as after waking. Consistency helps reveal the trend.</EmptyDescription></EmptyHeader></Empty>}</section></div></TabsContent></Tabs>
 <footer><span className="footer-brand">stride.</span><span>Small choices. A sustainable rhythm.</span><span>{profile.weight||'—'} kg starting · {profile.height?(profile.height/100).toFixed(2):'—'} m · 16:8</span></footer>
 <Dialog open={!!dialog} onOpenChange={v=>{if(!v&&!saving)setDialog(null)}}><DialogContent className="entry-dialog"><DialogHeader><DialogTitle>{dialog==='meal'?'Build your meal entry':dialog==='exercise'?'Log your movement':dialog==='weight'?'A simple weight check-in':'Your profile & eating window'}</DialogTitle><DialogDescription>{dialog==='profile'?'Adjust your schedule and optional nutrition guide.':`Adding to ${date}. Entries are saved only in this browser.`}</DialogDescription></DialogHeader>{formError&&<div className="notice error" role="alert">{formError}</div>}{dialog==='meal'&&<MealForm draft={draft} saving={saving} onSave={(d,p)=>save('meal',d,p)}/>} {dialog==='exercise'&&<ExerciseForm saving={saving} onSave={d=>save('exercise',d)}/>} {dialog==='profile'&&<ProfileForm profile={profile} saving={saving} onSave={d=>save('profile',d)}/>} {dialog==='weight'&&<form className="form" onSubmit={e=>{e.preventDefault();void save('weight',{kg:Number(new FormData(e.currentTarget).get('kg'))})}}><label>Weight (kg)<input name="kg" type="number" min="30" max="350" step="0.1" defaultValue={latest||''} required/></label><p className="tiny">Saved to the selected journal date: {date}.</p><button className="primary" disabled={saving}>{saving?'Saving…':'Save weigh-in'}</button></form>}</DialogContent></Dialog>
 <AlertDialog open={!!deleting} onOpenChange={v=>{if(!v&&!saving)setDeleting(null)}}><AlertDialogContent><AlertDialogTitle>Delete this entry?</AlertDialogTitle><AlertDialogDescription>The saved entry and any attached photo will be removed. This cannot be undone.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel disabled={saving}>Keep entry</AlertDialogCancel><AlertDialogAction disabled={saving} onClick={e=>{e.preventDefault();void remove()}}>{saving?'Deleting…':'Delete entry'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </main>
}
function MealForm({draft,saving,onSave}:{draft?:{name:string;items:Portion[]};saving:boolean;onSave:(data:unknown,photo?:File)=>void}){
 const [name,setName]=useState(draft?.name||''),[items,setItems]=useState<Portion[]>(draft?.items.map(i=>({...i}))||[]),[food,setFood]=useState('chicken'),[grams,setGrams]=useState('150'),[mode,setMode]=useState('ingredients'),[photo,setPhoto]=useState<File>(),[preview,setPreview]=useState(''),[photoError,setPhotoError]=useState('');
 const [manual,setManual]=useState({calories:0,protein:0,carbs:0,fat:0,fiber:0});
 const numbers=mode==='ingredients'?nutrition(items):manual;
 useEffect(()=>{if(!photo){setPreview('');return}const url=URL.createObjectURL(photo);setPreview(url);return()=>URL.revokeObjectURL(url)},[photo]);
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(mode==='ingredients'&&!items.length){setPhotoError('Add at least one food, or use nutrition-label values.');return}onSave({name,time:String(f.get('time')),...Object.fromEntries(Object.entries(numbers).map(([k,v])=>[k,Math.round(v*10)/10])),notes:String(f.get('notes')),items:mode==='ingredients'?items:[]},photo)}
 return <form className="form" onSubmit={submit}><label className="photo-upload">{preview?<img src={preview} alt="Selected meal"/>:<Camera size={28}/>}<strong>{photo?'Change meal photo':'Add a meal photo'}</strong><span>JPG, PNG or WebP · up to 5 MB · optional</span><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{setPhotoError('');const f=e.target.files?.[0];if(f&&(f.size>5*1024*1024||!['image/jpeg','image/png','image/webp'].includes(f.type))){setPhotoError('Choose a JPG, PNG, or WebP smaller than 5 MB.');e.target.value='';return}setPhoto(f)}}/></label><p className="tiny">The photo is a visual record. Confirm foods and portions below; image recognition is not connected.</p>{photoError&&<p className="error-text" role="alert">{photoError}</p>}<div className="form-grid"><label>Meal name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Chicken rice bowl" maxLength={120} required/></label><label>Time eaten<input name="time" type="time" defaultValue={new Date().toTimeString().slice(0,5)} required/></label></div>
 <Tabs value={mode} onValueChange={setMode}><TabsList><TabsTrigger value="ingredients">Foods & portions</TabsTrigger><TabsTrigger value="label">Nutrition label</TabsTrigger></TabsList><TabsContent value="ingredients"><div className="food-picker"><label>Food<Choice value={food} onChange={setFood} label="Food" items={foods.map(f=>({value:f.id,label:f.name}))}/></label><label>Grams<input type="number" min="1" max="3000" step="1" value={grams} onChange={e=>setGrams(e.target.value)}/></label><button type="button" className="secondary" onClick={()=>{const g=Number(grams);if(g>=1&&g<=3000&&items.length<40){setItems([...items,{id:food,grams:g}]);setPhotoError('')}}} disabled={!grams||Number(grams)<1||Number(grams)>3000||items.length>=40}>Add</button></div>{items.map((i,index)=><div className="portion-row" key={index}><span>{foods.find(f=>f.id===i.id)?.name}</span><strong>{i.grams} g</strong><button type="button" className="icon-button" aria-label={'Remove '+foods.find(f=>f.id===i.id)?.name} onClick={()=>setItems(items.filter((_,j)=>j!==index))}><Trash2 size={14}/></button></div>)}<p className="tiny">Use edible portions. Include oils, sauces and drinks. If a food is missing, enter nutrition-label totals instead.</p></TabsContent><TabsContent value="label"><p className="tiny">Enter totals for the entire portion you ate, not per 100 g.</p><div className="manual-grid">{Object.entries(manual).map(([k,v])=><label key={k}>{k==='calories'?'Energy (kcal)':k[0].toUpperCase()+k.slice(1)+' (g)'}<input type="number" min="0" max="20000" step="0.1" value={v} onChange={e=>setManual({...manual,[k]:Number(e.target.value)})} required/></label>)}</div></TabsContent></Tabs>
 <div className="nutrition-preview"><div><strong>{num(numbers.calories)}</strong><span>kcal · estimate</span></div><div><strong>{num(numbers.protein)} g</strong><span>Protein</span></div><div><strong>{num(numbers.carbs)} g</strong><span>Carbs</span></div><div><strong>{num(numbers.fat)} g</strong><span>Fat</span></div></div><label>Notes<textarea name="notes" maxLength={3000} placeholder="Sauces, preparation, hunger, or anything to remember" rows={2}/></label><p className="tiny">Generic food values are rounded approximations. Check packaging or <a href="https://fdc.nal.usda.gov/" target="_blank" rel="noreferrer">USDA FoodData Central</a> when you need a closer match.</p><button className="primary full" disabled={saving}>{saving?'Saving your meal…':'Save meal & estimate'}</button></form>
}
function ExerciseForm({saving,onSave}:{saving:boolean;onSave:(d:unknown)=>void}){const[type,setType]=useState('Running'),[intensity,setIntensity]=useState('Moderate');return <form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({type,intensity,minutes:Number(f.get('minutes')),notes:String(f.get('notes'))})}}><label>Activity<Choice value={type} onChange={setType} label="Activity" items={simple(['Running','Tennis','Muay Thai','Walking','Strength','Recovery'])}/></label><div className="form-grid"><label>Duration (minutes)<input name="minutes" type="number" min="1" max="300" defaultValue="45" required/></label><label>Effort<Choice value={intensity} onChange={setIntensity} label="Effort" items={simple(['Easy','Moderate','Hard'])}/></label></div><label>Session notes<textarea name="notes" rows={3} maxLength={2000} placeholder="Distance, rounds, how you felt, or recovery notes"/></label><p className="tiny">Sessions stay separate from food totals. Calorie burn varies too much to automatically adjust your eating plan.</p><button className="primary" disabled={saving}>{saving?'Saving…':'Save session'}</button></form>}
function ProfileForm({profile,saving,onSave}:{profile:Profile;saving:boolean;onSave:(p:Profile)=>void}){const [start,setStart]=useState(profile.start),[sex,setSex]=useState(profile.sex||'unset');const[h,m]=start.split(':').map(Number);return <form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const calorieTarget=Number(f.get('target'));if(calorieTarget>0&&calorieTarget<1500){toast.error('Choose a clinician-guided target of at least 1,500 kcal here, or leave it blank.');return}onSave({weight:Number(f.get('weight')),height:Number(f.get('height')),goalWeight:Number(f.get('goalWeight')),age:f.get('age')?Number(f.get('age')):'',sex:sex==='unset'?'':sex,start,preferences:String(f.get('preferences')),calorieTarget})}}><div className="form-grid"><label>Starting weight (kg)<input name="weight" type="number" min="30" max="350" step="0.1" defaultValue={profile.weight||''} required/></label><label>Height (cm)<input name="height" type="number" min="120" max="230" defaultValue={profile.height||''} required/></label><label>Longer-term goal weight (kg, optional)<input name="goalWeight" type="number" min="30" max="350" step="0.1" defaultValue={profile.goalWeight||''}/></label><label>Age (optional, adults only)<input name="age" type="number" min="18" max="100" defaultValue={profile.age}/></label><label>Sex (optional)<Choice value={sex} onChange={setSex} label="Sex" items={[{value:'unset',label:'Not specified'},{value:'male',label:'Male'},{value:'female',label:'Female'}]}/></label></div><label>Eating window starts<input type="time" value={start} onChange={e=>setStart(e.target.value)} required/></label><div className="window-result"><Clock3 size={18}/> Eat {start}–{clockLabel(h*60+m+480)} · fast the remaining 16 hours</div><label>Daily calorie guide (optional)<input name="target" type="number" min="0" max="6000" step="1" defaultValue={profile.calorieTarget||''} placeholder="Use a target agreed with your dietitian"/></label><p className="tiny">No calorie target is calculated automatically. Age and sex are saved as profile notes. Needs vary with training and health. The sample menu is adjustable; 1,500 kcal is a software minimum, not a recommendation for you.</p><label>Food preferences or allergies<textarea name="preferences" maxLength={1000} defaultValue={profile.preferences} rows={2} placeholder="Your reference notes"/></label><p className="tiny">These notes are stored for you. They do not automatically filter the example menu; check every ingredient.</p><button className="primary" disabled={saving}>{saving?'Saving…':'Save settings'}</button></form>}
