import {z} from 'zod';
import {defaultProfile} from './nutrition';
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v);
const amount=z.number().finite().min(0).max(20000);
const meal=z.object({name:z.string().trim().min(1).max(120),time:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),calories:amount,protein:amount,carbs:amount,fat:amount,fiber:amount,notes:z.string().max(3000),items:z.array(z.object({id:z.string().max(100),grams:z.number().min(1).max(3000)})).max(40)});
const exercise=z.object({type:z.enum(['Running','Tennis','Muay Thai','Walking','Strength','Recovery']),minutes:z.number().min(1).max(300),intensity:z.enum(['Easy','Moderate','Hard']),notes:z.string().max(2000)});
const weight=z.object({kg:z.number().min(30).max(350)});
const optionalMeasurement=(min:number,max:number)=>z.number().finite().refine(v=>v===0||(v>=min&&v<=max));
const profileSchema=z.object({weight:optionalMeasurement(30,350),height:optionalMeasurement(120,230),goalWeight:optionalMeasurement(30,350),age:z.union([z.literal(''),z.number().min(18).max(100)]),sex:z.enum(['','male','female']),start:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),preferences:z.string().max(1000),calorieTarget:z.number().min(0).max(6000).refine(v=>v===0||v>=1500)});
const base={id:z.string().uuid(),day:date,createdAt:z.string().datetime()};
const entrySchema=z.discriminatedUnion('kind',[
 meal.extend({...base,kind:z.literal('meal')}),exercise.extend({...base,kind:z.literal('exercise')}),weight.extend({...base,kind:z.literal('weight')})]);
type Entry=z.infer<typeof entrySchema>&{photo?:Blob};
let connection:Promise<IDBDatabase>|undefined;
function db(){if(!connection)connection=new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('stride-journal-v1',1);request.onupgradeneeded=()=>{request.result.createObjectStore('entries',{keyPath:'id'});request.result.createObjectStore('settings')};request.onsuccess=()=>{const result=request.result;result.onversionchange=()=>{result.close();connection=undefined};resolve(result)};request.onerror=()=>{connection=undefined;reject(new Error('Browser storage is unavailable. Allow site data and try again.'))};request.onblocked=()=>reject(new Error('Close other Stride tabs and retry.'))});return connection}
function request<T>(r:IDBRequest<T>){return new Promise<T>((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function completion(t:IDBTransaction){return new Promise<void>((resolve,reject)=>{t.oncomplete=()=>resolve();t.onabort=t.onerror=()=>reject(new Error('Could not save to this browser. Check available storage space and site-data permissions.'))})}
export async function loadJournal(){const database=await db();const t=database.transaction(['settings','entries'],'readonly');const [profile,entries]=await Promise.all([request(t.objectStore('settings').get('profile')),request(t.objectStore('entries').getAll())]);return {profile:profile?profileSchema.parse({...defaultProfile,...profile}):null,records:(entries as Entry[]).sort((a,b)=>b.day.localeCompare(a.day)||b.createdAt.localeCompare(a.createdAt)).map(({photo,...e})=>({...e,hasPhoto:!!photo}))}}
async function validatePhoto(photo:Blob){if(photo.size>5*1024*1024)throw new Error('Choose a photo smaller than 5 MB.');const b=new Uint8Array(await photo.slice(0,12).arrayBuffer());const type=b[0]===255&&b[1]===216&&b[2]===255?'image/jpeg':b[0]===137&&b[1]===80&&b[2]===78&&b[3]===71?'image/png':new TextDecoder().decode(b.slice(0,4))==='RIFF'&&new TextDecoder().decode(b.slice(8,12))==='WEBP'?'image/webp':null;if(!type)throw new Error('Use a JPG, PNG or WebP photo.');return new Blob([photo],{type})}
export async function saveJournal(kind:string,day:string,data:unknown,photo?:Blob){const database=await db();if(kind==='profile'){const profile=profileSchema.parse(data);const t=database.transaction('settings','readwrite');const done=completion(t);t.objectStore('settings').put(profile,'profile');await done;return}const entry=entrySchema.parse({...(typeof data==='object'&&data?data:{}),kind,day,id:crypto.randomUUID(),createdAt:new Date().toISOString()}) as Entry;if(photo){if(kind!=='meal')throw new Error('Only meals accept photos.');entry.photo=await validatePhoto(photo)}const t=database.transaction('entries','readwrite');const done=completion(t);t.objectStore('entries').add(entry);await done;void navigator.storage?.persist?.().catch(()=>false)}
export async function deleteEntry(id:string){z.string().uuid().parse(id);const database=await db();const t=database.transaction('entries','readwrite');const done=completion(t);t.objectStore('entries').delete(id);await done}
export async function getPhoto(id:string){const database=await db();const entry=await request(database.transaction('entries').objectStore('entries').get(id)) as Entry|undefined;return entry?.photo||null}
function encode(blob:Blob){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Could not read a photo for backup.'));reader.readAsDataURL(blob)})}
export async function exportJournal(){const database=await db();const t=database.transaction(['settings','entries'],'readonly');const [profile,records]=await Promise.all([request(t.objectStore('settings').get('profile')),request(t.objectStore('entries').getAll())]);const entries=[];for(const {photo,...record} of records as Entry[])entries.push({...record,photo:photo?await encode(photo):null});return new Blob([JSON.stringify({format:'stride-backup',version:1,exportedAt:new Date().toISOString(),profile:profile||defaultProfile,entries})],{type:'application/json'})}
export async function importJournal(file:File){if(file.size>100*1024*1024)throw new Error('Choose a Stride backup smaller than 100 MB.');let raw;try{raw=JSON.parse(await file.text())}catch{throw new Error('This is not a valid JSON backup.')}const backup=z.object({format:z.literal('stride-backup'),version:z.literal(1),profile:profileSchema,entries:z.array(z.unknown()).max(10000)}).parse(raw);const entries:Entry[]=[];for(const value of backup.entries){const entry=entrySchema.parse(value) as Entry;const photo=(value as {photo?:unknown}).photo;if(photo){if(entry.kind!=='meal'||typeof photo!=='string'||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(photo))throw new Error('The backup contains an invalid photo.');const base64=photo.split(',')[1];if(base64.length>7*1024*1024)throw new Error('A backup photo is too large.');const bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0));entry.photo=await validatePhoto(new Blob([bytes]))}entries.push(entry)}const database=await db();const t=database.transaction(['settings','entries'],'readwrite');const done=completion(t);t.objectStore('settings').put(backup.profile,'profile');const store=t.objectStore('entries');let imported=0;for(const entry of entries){const r=store.getKey(entry.id);r.onsuccess=()=>{if(r.result===undefined){store.add(entry);imported++}}}await done;return imported}
